version: "3"
services:
  web:
    image: bootcamps/auth
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]