FROM node:carbon-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "yarn.lock", "./"]

# RUN npm install --production --silent && mv node_modules ../
RUN apk update \
  && apk add yarn \
  && yarn --production && mv node_modules ../

COPY ./src/. .
EXPOSE 8080
CMD node --experimental-modules server.js